# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9dae7c5a4b595eae65e0fd3dbdc81135c556d6a6353d1da44ffd445eb9425d29e9bd222d5b3b382f9272bddcbe8595596611a2f2270de365a0bc88e717e7fd2

test:
  secret_key_base: bfb4680348d37a0abac7d01a23dc6ed268329d11103443be50557bfdc8f28718873ff2261a55a79deb2f13c7165fdf005259616a5aed735d8856c6a06c8a2eb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
